apiVersion: apps/v1
kind: Deployment
metadata:
  name: psiapp
spec:
  selector:
    matchLabels:
      app: prod-msauth
      environment: prod
  template:
    metadata:
      labels:
        app: prod-msauth